# Generated by Django 5.2.7 on 2025-11-07 10:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_middle_name_alter_customuser_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(max_length=150, unique=True, validators=[django.core.validators.RegexValidator(message='Username must contain only letters, numbers, and underscores, plus other validations.', regex='^([a-z_][a-z0-9_]{2,9})$')]),
        ),
    ]
