# Generated by Django 5.2.7 on 2025-11-07 11:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(max_length=150, unique=True, validators=[django.core.validators.RegexValidator(message='Please enter a valid username between 3 and 10 characters long. It must start with a lowercase letter (a-z) or an underscore (_), and can only contain lowercase letters, numbers, or underscores.', regex='^([a-z_][a-z0-9_]{2,9})$')]),
        ),
    ]
